# Generated by Django 4.2.11 on 2024-06-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_chat_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='therapist',
        ),
    ]
